<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

   'Match' => 'Partido',
   'set 1' => 'Serie 1',
   'set 2' => 'Serie 2',
   'set 3' => 'Serie 3',
   'set 4' => 'Serie 4',
   'set 5' => 'Serie 5',
   'Aces' => 'Aces',
   'Double Faults' => 'Dobles faltas',
   'First Services' => 'Primeros saques',
   'First Serve Points Won' => 'Puntos ganados con primer saque',
   'Second Serve Points Won' => 'Puntos ganados con segundo saque',
   'Break Points Saved' => 'Puntos de rotura salvados',
   'Services Games Played' => 'Juegos jugados al saque',
   'First Return Points Won' => 'Puntos ganados en primer retorno',
   'Second Return Points Won' => 'Puntos ganados en segundo retorno',
   'Break Points Converted' => 'Puntos de rotura convertidos',
   'Return Games Played' => 'Juegos jugados al resto',
   'Total Serve Points Won' => 'Total de puntos ganados al saque',
   'Total Return Points Won' => 'Total de puntos ganados al resto',
   'Total Points Won' => 'Puntos totales ganados',
   'Longest Points Won Streak' => 'Racha más larga de puntos ganados',
   'Average Points Duration In Seconds' => 'Duración promedio de los puntos en segundos',
   'Players list will be available soon' => 'La lista de jugadores estará disponible pronto.',
   'NO UPCOMING TOURNAMENTS AT THE MOMENT. PLEASE TUNE IN LATER.' => 'POR EL MOMENTO NO HAY PRÓXIMOS TORNEOS. POR FAVOR CONÉCTESE MÁS TARDE.',
   'NO MATCHES AT THE MOMENT. PLEASE TUNE IN LATER.' => 'NO HAY PARTIDOS POR EL MOMENTO. POR FAVOR CONÉCTESE MÁS TARDE.',
   'NO COMPLETED TOURNAMENTS AT THE MOMENT. PLEASE TUNE IN LATER.' => 'POR EL MOMENTO NO HAY TORNEOS COMPLETADOS. POR FAVOR CONÉCTESE MÁS TARDE.',
   'News' => 'Noticias',
   'Videos' => 'Vídeos',
   'Tournaments' => 'Torneos',
   'Gallery' => 'Galería',
   'January' => 'Enero',
   'February' => 'Febrero',
   'March' => 'Marzo',
   'April' => 'Abril',
   'May' => 'Mayo',
   'June' => 'Junio',
   'July' => 'Julio',
   'August' => 'Agosto',
   'September' => 'Septiembre',
   'October' => 'Octubre',
   'November' => 'Noviembre',
   'December' => 'Diciembre',
   'Your password has been changed' => 'Tu contraseña ha sido cambiada',
   'The old password you have entered is incorrect, Please enter current password' => 'La contraseña anterior que ingresó es incorrecta. Ingrese la contraseña actual.',
   'Invalid email or password please try again' => 'Correo electrónico o contraseña no válidos, inténtalo de nuevo.',
   'An account with this email address does not exist. Please sign up to create a new account.' => 'No existe una cuenta con esta dirección de correo electrónico. Regístrese para crear una nueva cuenta.',
   'You account is inactive. Please contact admin for more information.' => 'Su cuenta está inactiva. Póngase en contacto con el administrador para obtener más información.',
   'Approval not received' => 'Aprobación no recibida',
   'User not Found.' => 'Usuario no encontrado.',
   'Unauthorized access' => 'Acceso no autorizado',
   'Please check your email for further information.' => 'Por favor revisa tu correo electrónico para más información.',
   'You are not registered with this email' => 'No estás registrado con este correo electrónico',
   'No matches available.' => 'No hay coincidencias disponibles.',
];
